jobs:
- job: ${{ parameters.arch }}
  pool:
    vmImage: ubuntu-latest
  variables:
    BUILD_ARCH: ${{ parameters.arch }}
    MOCK_ARCH: ${{ parameters.mock_arch }}
    VM_IMAGE_URN: ${{ parameters.vm_image_urn }}
    VM_SIZE: ${{ parameters.vm_size }}
    RESOURCE_GROUP: ${{ parameters.resource_group }}
    BUILD_GIT: ${{ parameters.build_git }}
    BUILD_BRANCH: ${{ parameters.build_branch }}
    BUILD_SCRIPT: ${{ parameters.build_script }}
    BUILD_DEPS: ${{ parameters.build.deps }}
    TAR_DIR: ${{ parameters.tar_dir }}
    #import parameters as variables from azure-pipelines.yml

  steps:
  - task: AzureCLI@1
    inputs:
      azureSubscription: ${{ parameters.azure_sub }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo 'az vm image accept-terms --urn '${VM_IMAGE_URN}
        az vm image accept-terms --urn ${VM_IMAGE_URN}
    displayName: 'Accepting Azure VM image terms'

  - task: AzureCLI@1
    inputs:
      azureSubscription: ${{ parameters.azure_sub }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        BUILD_ID=$RANDOM
        echo 'Build ID '$BUILD_ID
        BUILD_NAME='Build-'${BUILD_ARCH}'-'${BUILD_ID}
        echo 'Build Name '${BUILD_NAME}
        echo "##vso[task.setvariable variable=BUILD_NAME;isOutput=true]${BUILD_NAME}"
        echo 'Resource Group '${RESOURCE_GROUP}
        echo 'Image '${VM_IMAGE_URN}
        az vm create \
          --resource-group ${RESOURCE_GROUP} \
          --name ${BUILD_NAME} \
          --image ${VM_IMAGE_URN} \
          --size ${VM_SIZE} \
          --admin-username azureuser \
          --generate-ssh-keys
    displayName: 'Spinning up new Azure VM'

  - task: AzureCLI@1
    inputs:
      azureSubscription: ${{ parameters.azure_sub }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        VM_IP_ADDR=$(az vm show -d -g ${RESOURCE_GROUP} -n ${BUILD_NAME} --query publicIps -o tsv)
        echo 'VM IP address '${VM_IP_ADDR}
        echo "##vso[task.setvariable variable=VM_IP_ADDR;isOutput=true]${VM_IP_ADDR}"
    displayName: 'Getting IP address of new Azure VM'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'Adding to /etc/ssh/sshd_config'
        sudo tee -a / > /dev/null <<EOT
        Host ${BUILD_NAME}
            Hostname ${VM_IP_ADDR}
            StrictHostKeyChecking no
        EOT
        echo 'Reading back /etc/ssh/sshd_config'
        sudo cat /etc/ssh/sshd_config
        sudo systemctl restart ssh
    displayName: 'Configuring SSH'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        ssh azureuser@${VM_IP_ADDR} echo 'hello world'
    displayName: 'Logging into Azure VM via ssh'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: ssh azureuser@${VM_IP_ADDR} ${BUILD_DEPS}
    displayName: 'Installing Dependencies'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: ssh azureuser@${VM_IP_ADDR} git clone -b ${BUILD_BRANCH} ${BUILD_GIT}
    displayName: 'Cloning Build GitHub'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: ssh azureuser@${VM_IP_ADDR} bash ${BUILD_SCRIPT} ${BUILD_ARCH}
    displayName: 'Running Build Script'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: scp -o "StrictHostKeyChecking no" azureuser@${VM_IP_ADDR}:/${TAR_DIR}/install.tar.gz $(Build.ArtifactStagingDirectory)/install_$BUILD_ARCH_rootfs.tar.gz
    displayName: 'Downloading .tar.gz to Artifacts'

- job: Clean
  dependsOn: ${{ parameters.arch }}
  pool:
    vmImage: ubuntu-latest
  variables:
    BUILD_NAME: $[ dependencies.${{ parameters.arch }}.outputs['setvarStep.myOutputVar'] ]
    RESOURCE_GROUP: ${{ parameters.resource_group }}
  steps:
  - task: AzureCLI@1
    inputs:
    azureSubscription: ${{ parameters.azure_sub }}
    scriptLocation: 'inlineScript'
    inlineScript: |
     echo 'removing '${BUILD_NAME}' from '${RESOURCE_GROUP}
     az vm delete \
      --resource-group ${RESOURCE_GROUP} \
      --name ${BUILD_NAME} \
      --yes
    displayName: 'Shutting down Azure VMs'