jobs:
- job: ${{ parameters.arch }}
  pool:
    vmImage: ubuntu-latest
  variables:
    BUILD_ARCH: ${{ parameters.arch }}
    MOCK_ARCH: ${{ parameters.mock_arch }}

  steps:
  - script: sudo dnf -y install qemu-user-static git systemd systemd-container #mock
    displayName: 'Installing dependencies'

  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Pay-As-You-Go(32f0131f-84dc-4502-99b2-c0a74a1423ce)'
      scriptLocation: 'inlineScript'
      inlineScript: 'echo ''hello world'''
