jobs:
- job: ${{ parameters.arch }}
  pool:
    vmImage: ubuntu-latest
  variables:
    BUILD_ARCH: ${{ parameters.arch }}
    MOCK_ARCH: ${{ parameters.mock_arch }}

  steps:
  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Pay-As-You-Go(32f0131f-84dc-4502-99b2-c0a74a1423ce)'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az vm create \
          --resource-group Fedora \
          --name Build \
          --image fedora30 \
          --admin-username azureuser \
          --generate-ssh-keys
        vmipaddress=$(az vm show -d -g Fedora -n Build --query publicIps -o tsv)

  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Pay-As-You-Go(32f0131f-84dc-4502-99b2-c0a74a1423ce)'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az vm delete \
          --resource-group Fedora \
          --name Build \
          --yes
