jobs:
- job: ${{ parameters.arch }}
  pool:
    vmImage: ubuntu-latest
  variables:
    BUILD_ARCH: ${{ parameters.arch }}
    MOCK_ARCH: ${{ parameters.mock_arch }}
    RESOURCE_GROUP: 'Fedora'
    VM_IMAGE_URN: 'tunnelbiz:fedora:fedora30:0.0.3'
    #AZURE_SUB is set globally in Azure Pipelines

  steps:
  - task: AzureCLI@1
    inputs:
      azureSubscription: AZURE_SUB
      scriptLocation: 'inlineScript'
      inlineScript: |
        AZURE_SUB: ''
        az vm image accept-terms --urn ${VM_IMAGE_URN}
    displayName: 'Accepting Azure VM image terms'

  - task: AzureCLI@1
    inputs:
      azureSubscription: AZURE_SUB
      scriptLocation: 'inlineScript'
      inlineScript: |
        BUILD_ID=$RANDOM
        echo 'Build ID '$RANDOM
        BUILD_NAME='Build-'${BUILD_ARCH}'-'${BUILD_ID}
        echo 'Build Name '$BUILD_NAME
        az vm create \
          --resource-group ${RESOURCE_GROUP} \
          --name ${BUILD_NAME} \
          --image ${VM_IMAGE_URN} \
          --admin-username azureuser \
          --generate-ssh-keys
    displayName: 'Spinning up new Azure VM'

  - task: AzureCLI@1
    inputs:
      azureSubscription: ${AZURE_SUB}
      scriptLocation: 'inlineScript'
      inlineScript: |
        VM_IP_ADDR=$(az vm show -d -g ${RESOURCE_GROUP} -n ${BUILD_NAME} --query publicIps -o tsv)
    displayName: 'Getting IP address of new Azure VM'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: ssh -o "StrictHostKeyChecking no" azureuser@${VM_IP_ADDR} "echo 'hello world'"
    displayName: 'Logging into Azure VM via ssh'
  
  - task: AzureCLI@1
    inputs:
      azureSubscription: ${AZURE_SUB}
      scriptLo cation: 'inlineScript'
      inlineScript: |
        az vm delete \
          --resource-group ${RESOURCE_GROUP} \
          --name ${BUILD_NAME} \
          --yes
    displayName: 'Shutting down Azure VM'