trigger:
- master

jobs:
- template: architecture_template.yml
  parameters:
    arch: amd64
    mock_arch: amd64
- template: architecture_template.yml
  parameters:
    arch: arm64
    mock_arch: aarch64