trigger:
- master

jobs:
- template: architecture_template.yml
  parameters:
    arch: amd64
    mock_arch: x86_64
    resource_group: 'Fedora'
    vm_image_urn: 'tunnelbiz:fedora:fedora30:0.0.3'
- template: architecture_template.yml
  parameters:
    arch: arm64
    mock_arch: aarch64